Add apisocks5
mullvad/mullvadvpn-app-binaries pull request #109
Opened 2024-05-08 12:28 UTC by hulthe

Add [mullvad/apisocks5](https://github.com/mullvad/apisocks5.git) as a submodule and include it in build scripts

2024-05-08 16:54 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @hulthe)

___
*[`Dockerfile` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NxO6c3LCQ_TdahBKiRt:-NxO6c3LCQ_TdahBKiRu:b-7srtvm) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/aead381749b318eb0a7a238a8130d2f3bd4347fe/Dockerfile#L25)):*
> ```Dockerfile
> RUN if [ "$(uname -m)" = "x86_64" ]; then \
>         curl -fLO https://go.dev/dl/go1.22.3.linux-amd64.tar.gz &&\
>         echo "8920ea521bad8f6b7bc377b4824982e011c19af27df88a815e3586ea895f1b36  go1.22.3.linux-amd64.tar.gz" \
> ```

Should we maybe discuss if it is ideal to keep *yet another* go compiler and hash around? We already have way too many places this information is duplicated. If we are not using our "regular" app building container that already has go in it, then maybe we should consider using the container definition already existing in `apisocks5`? They recently downgraded their own go version to 1.21 to match our expectations, but then we end up using 1.22 which seems counterproductive.


<!-- Sent from Reviewable.io -->

2024-05-08 16:55 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @hulthe)

___
*[`Makefile` line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NxO7GVZC3q56o3yCtS2:-NxO7GVZC3q56o3yCtS3:b-4nokza) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/aead381749b318eb0a7a238a8130d2f3bd4347fe/Makefile#L180)):*
> ```Makefile
> 	cd apisocks5;\
> 		go build -o ../$(TARGET)/ &&\
> 		$(STRIP) ../$(TARGET)/apisocks5*
> ```

The relay software team has already been so kind as to prepare all of this for us. I don't think we should duplicate all the build setup unless we have a good reason to https://github.com/mullvad/apisocks5/blob/e15a0dc2254c2c81da10d1b8b49a4f2ea2422c2b/Makefile#L65-L72


<!-- Sent from Reviewable.io -->

2024-05-13 09:26 UTC, hulthe reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`Dockerfile` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NxO6c3LCQ_TdahBKiRt:-Nxl8kEg84UYDMLcDTDY:b-5mejh0) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/aead381749b318eb0a7a238a8130d2f3bd4347fe/Dockerfile#L25)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Should we maybe discuss if it is ideal to keep *yet another* go compiler and hash around? We already have way too many places this information is duplicated. If we are not using our "regular" app building container that already has go in it, then maybe we should consider using the container definition already existing in `apisocks5`? They recently downgraded their own go version to 1.21 to match our expectations, but then we end up using 1.22 which seems counterproductive.
</blockquote></details>

Is there a reason we're sticking to an older go compiler?
___
*[`Makefile` line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NxO7GVZC3q56o3yCtS2:-Nxl7JkE9o784eiFPyue:b-x4blb1) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/aead381749b318eb0a7a238a8130d2f3bd4347fe/Makefile#L180)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The relay software team has already been so kind as to prepare all of this for us. I don't think we should duplicate all the build setup unless we have a good reason to https://github.com/mullvad/apisocks5/blob/e15a0dc2254c2c81da10d1b8b49a4f2ea2422c2b/Makefile#L65-L72
</blockquote></details>

A good reason might be to keep the build process consistent for all the binaries. i.e., just run `./container-run.sh make foo [TARGET=bar]`, instead of having a different set of commands for some binaries. Although if we removed the requirement of calling ./container-run on the makefile then we could simply have it call into `apisocks5/makefile` and do whatever.


<!-- Sent from Reviewable.io -->

2024-05-14 10:50 UTC, dlon reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109)* status: all files reviewed, 3 unresolved discussions (waiting on @faern and @hulthe)

___
*[`apisocks5` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NxqIjKs4O9BsRTE49oi:-NxqIjKt14OB9Jo4Jiik:bf8ckfs) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/aead381749b318eb0a7a238a8130d2f3bd4347fe/apisocks5#L1)):*
> ```
> Subproject commit e15a0dc2254c2c81da10d1b8b49a4f2ea2422c2b
> ```

This should ideally point to a signed tag/release. It seems to point to `master` right now.
___
*[`Makefile` line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NxO7GVZC3q56o3yCtS2:-NxqgI7a3QjaJeMVdFQh:b1dtqwd) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/aead381749b318eb0a7a238a8130d2f3bd4347fe/Makefile#L180)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

A good reason might be to keep the build process consistent for all the binaries. i.e., just run `./container-run.sh make foo [TARGET=bar]`, instead of having a different set of commands for some binaries. Although if we removed the requirement of calling ./container-run on the makefile then we could simply have it call into `apisocks5/makefile` and do whatever.
</blockquote></details>

Could we not run `cd apisocks5 && $(MAKE) build`? That target seems to use their Docker container. I think that that should just work regardless of whether it's called from `container-run.sh` or not.

Also, is `./container-run.sh` a requirement? It shouldn't be.


<!-- Sent from Reviewable.io -->

2024-05-14 11:02 UTC, hulthe reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109)* status: all files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`Makefile` line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NxO7GVZC3q56o3yCtS2:-Nxql4DD1G_iOpfCp1sC:bi8bf9e) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/aead381749b318eb0a7a238a8130d2f3bd4347fe/Makefile#L180)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could we not run `cd apisocks5 && $(MAKE) build`? That target seems to use their Docker container. I think that that should just work regardless of whether it's called from a container `container-run.sh` or not.

Also, is `./container-run.sh` a requirement? It shouldn't be.
</blockquote></details>

Ah cool. I didn't think you could nest podmans


<!-- Sent from Reviewable.io -->

2024-05-14 11:03 UTC, hulthe reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109)* status: all files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`Makefile` line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NxO7GVZC3q56o3yCtS2:-NxqlK9xBm2TScVFFz-e:b-gung2l) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/aead381749b318eb0a7a238a8130d2f3bd4347fe/Makefile#L180)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Ah cool. I didn't think you could nest podmans
</blockquote></details>

The dockerfile used by apisocks5 doesn't work on arm tho, so we'd need to fix that


<!-- Sent from Reviewable.io -->

2024-05-15 13:33 UTC, faern requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @hulthe)

___
*[`Dockerfile` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NxO6c3LCQ_TdahBKiRt:-NxwRZg_4H8pz_M3IQTg:b-p10w3i) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/aead381749b318eb0a7a238a8130d2f3bd4347fe/Dockerfile#L25)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Is there a reason we're sticking to an older go compiler?
</blockquote></details>

Yes. Because it has to be compatible with wireguard-go. And wireguard-go in turn requires an ugly patch in order for it to work on Android: https://github.com/mullvad/mullvadvpn-app/blob/2b4637815036060b3a4398c30d8a770f9b642132/android/docker/Dockerfile#L17-L21

But it would also be very nice to not have two billion go checksums spread out all over :P
___
*[`Makefile` line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NxO7GVZC3q56o3yCtS2:-NxwS7YrD4tPkWXbruHY:b-z1icur) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/aead381749b318eb0a7a238a8130d2f3bd4347fe/Makefile#L180)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

The dockerfile used by apisocks5 doesn't work on arm tho, so we'd need to fix that
</blockquote></details>

It should not need to work on arm. apisocks5 is designed to be cross compiled from Linux for all targets. See the link I pasted at the top of this thread


<!-- Sent from Reviewable.io -->

2024-05-16 13:15 UTC, faern reviewed
We must also add this component to the `README.md`. How to build and how to bump the submodule.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-:-Ny0XenN22CuUH0WOZ-w:b-e1u58o)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @dlon and @hulthe)

___
*[`apisocks5` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NxqIjKs4O9BsRTE49oi:-Ny0XZe_71bwMaQmfw8m:b-3wdok2) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/aead381749b318eb0a7a238a8130d2f3bd4347fe/apisocks5#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This should ideally point to a signed tag/release. It seems to point to `master` right now.
</blockquote></details>

Indeed. Pointing to a tag is preferable if possible. 


<!-- Sent from Reviewable.io -->

2024-05-17 13:58 UTC, faern requested changes
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @dlon and @hulthe)

___
*[`Dockerfile` line 28 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-Ny5p9QC2vxGhWbqFvj8:-Ny5p9QC2vxGhWbqFvj9:br9wb70) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/bf0f602732aead44cd57807b2c6b6081b6cdf216/Dockerfile#L28)):*
> ```Dockerfile
> RUN curl -fLO https://go.dev/dl/${GO_FILENAME} &&\
>     echo "${GO_FILEHASH}  ${GO_FILENAME}" | sha256sum --check - &&\
>     tar -C /usr/local/ -xzf go1.22.3.linux-amd64.tar.gz &&\
> ```

You probably want `$GO_FILENAME` instead of repeating the name here?


<!-- Sent from Reviewable.io -->

2024-05-17 16:04 UTC, faern requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @dlon and @hulthe)

___
*[`Makefile` line 97 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-Ny6GWs29aSDEEXUt0j4:-Ny6GWs29aSDEEXUt0j5:bmkaj8x) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/bf4c8f57145c320993be31347858f7e2332cb17e/Makefile#L97)):*
> ```Makefile
> ifneq (,$(findstring windows,$(TARGET)))
> 	GOOS = windows
> 	GOARCH = amd64
> ```

This this not *always* overwritten by the setting of `GOARCH` below? There it is set in both the if and the else branch, so it's guaranteed to be set there?
___
*[`README.md` line 124 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-Ny6HL7L3ihtzRoghQtU:-Ny6HL7L3ihtzRoghQtV:bna2v8p) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/bf4c8f57145c320993be31347858f7e2332cb17e/README.md#L124)):*
> ```Markdown
> 
> # on macos
> # TODO: build instructions for x86 and arm
> ```

We should not need macOS build instructions. We will only build this from Linux for our own app. However you need instructions how to build *for* macOS. I only see Linux and Windows above.


<!-- Sent from Reviewable.io -->

2024-05-21 09:43 UTC, hulthe reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @dlon and @faern)

___
*[`Dockerfile` line 28 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-Ny5p9QC2vxGhWbqFvj8:-NyPXCj77HPwsyrpFViD:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/bf0f602732aead44cd57807b2c6b6081b6cdf216/Dockerfile#L28)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

You probably want `$GO_FILENAME` instead of repeating the name here?
</blockquote></details>

Done.
___
*[`Makefile` line 97 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-Ny6GWs29aSDEEXUt0j4:-NyPWlwtEUFlzqZhBjPU:b-fn8mpi) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/bf4c8f57145c320993be31347858f7e2332cb17e/Makefile#L97)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This this not *always* overwritten by the setting of `GOARCH` below? There it is set in both the if and the else branch, so it's guaranteed to be set there?
</blockquote></details>

:facepalm: 
___
*[`README.md` line 124 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-Ny6HL7L3ihtzRoghQtU:-NyPWpjUABGyK8SdSf_z:b-74m45f) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/bf4c8f57145c320993be31347858f7e2332cb17e/README.md#L124)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We should not need macOS build instructions. We will only build this from Linux for our own app. However you need instructions how to build *for* macOS. I only see Linux and Windows above.
</blockquote></details>

Ah, I assumed that cross compiling for macos wasnt possible. I'll need to fix up the makefile to support this then.


<!-- Sent from Reviewable.io -->

2024-05-21 11:02 UTC, dlon reviewed
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109)* status: all files reviewed, 4 unresolved discussions (waiting on @faern and @hulthe)

___
*[`Dockerfile` line 28 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-Ny5p9QC2vxGhWbqFvj8:-NyPmc6oDlNwecHau40v:b2qal73) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/bf0f602732aead44cd57807b2c6b6081b6cdf216/Dockerfile#L28)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It looks like the filename is still repeated for `tar`


<!-- Sent from Reviewable.io -->

2024-05-21 11:05 UTC, hulthe reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109)* status: all files reviewed, 4 unresolved discussions (waiting on @faern)

___
*[`Dockerfile` line 28 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-Ny5p9QC2vxGhWbqFvj8:-NyPon791oetCfBhw0we:bqhxw22) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/bf0f602732aead44cd57807b2c6b6081b6cdf216/Dockerfile#L28)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It looks like the filename is still repeated for `tar`
</blockquote></details>

I have contracted blindness today it seems


<!-- Sent from Reviewable.io -->

2024-05-21 14:11 UTC, hulthe reviewed
Regarding the submodule, I imagine the instructions will be the same as with openvpn, with the same signing key?

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-:-NyQUC5cBvQ47-GowxhK:b-rk4w5e)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`Dockerfile` line 28 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-Ny5p9QC2vxGhWbqFvj8:-NyQUQjVEklDM27avxhS:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/bf0f602732aead44cd57807b2c6b6081b6cdf216/Dockerfile#L28)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

I have contracted blindness today it seems
</blockquote></details>

Done
___
*[`README.md` line 124 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-Ny6HL7L3ihtzRoghQtU:-NyQUTYx74_mnjNya_I_:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/bf4c8f57145c320993be31347858f7e2332cb17e/README.md#L124)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Ah, I assumed that cross compiling for macos wasnt possible. I'll need to fix up the makefile to support this then.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-05-23 07:41 UTC, faern approved these changes
It's similar to bumping the other submodules, but with a different key. Relay software develop and release `apisocks5` so it should probably be a trusted key from someone in that team. But yeah, the overall instructions are 1) move to a release tag 2) make sure the release tag is properly GPG signed by a trusted person for that project we are consuming.

I do not think we should repeat key fingerprints in the readme for this one! Because the project is developed in house. We have other ways of exchanging keys securely. The only reason we keep the fingerprint of external projects around is because we don't have an internal source of truth for them in the same way as our own keys.

> Reviewed 1 of 3 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-:-NyZNpnl0uZ7Ugj8Oq6s:bgqp199)* status: all files reviewed, 1 unresolved discussion (waiting on @hulthe)

___
*[`Makefile` line 183 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NyZMe540_M7lkEeCCdk:-NyZMe540_M7lkEeCCdl:b-7d7jgh) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f6aab4c8adb91bdfe67ce110c292036df8528be8/Makefile#L183)):*
> ```Makefile
> apisocks5:
> 	cd apisocks5;\
> 	GOOS=$(GOOS) GOARCH=$(GOARCH) go build -ldflags="-s -w" -o ../$(TARGET)/
> ```

Nit: At least I am not super fluent in ld flags. I would personally prefer the long flags being passed and/or a comment here saying we strip and ignore warnings (why do we ignore warnings?)


<!-- Sent from Reviewable.io -->

2024-05-23 07:54 UTC, dlon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-:-NyZRHce2_50hZ4aug1Z:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @hulthe)



<!-- Sent from Reviewable.io -->

2024-05-23 08:39 UTC, hulthe reviewed
Added something to the readme

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-:-NyZadl68HrMRhgT_Otp:bc68tyv)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[`Makefile` line 183 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NyZMe540_M7lkEeCCdk:-NyZZOLBBgjMmi2-76dj:b-i8zcmo) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f6aab4c8adb91bdfe67ce110c292036df8528be8/Makefile#L183)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nit: At least I am not super fluent in ld flags. I would personally prefer the long flags being passed and/or a comment here saying we strip and ignore warnings (why do we ignore warnings?)
</blockquote></details>

There are no long flags :(
Note that these are flags to `go tool link`, not GNU ld as the name may imply. I've added a comment clarifying what the flags mean with a link to the docs.


<!-- Sent from Reviewable.io -->

2024-05-23 08:44 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-:-NyZbuk_AqTmwKaapL4p:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`Makefile` line 183 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/109#-NyZMe540_M7lkEeCCdk:-NyZba4iCJLBq86OJCr4:bf1dl6h) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/f6aab4c8adb91bdfe67ce110c292036df8528be8/Makefile#L183)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

There are no long flags :(
Note that these are flags to `go tool link`, not GNU ld as the name may imply. I've added a comment clarifying what the flags mean with a link to the docs.
</blockquote></details>

Aah. Of course. Thanks for the comments, much better :pray: 


<!-- Sent from Reviewable.io -->

2024-05-23 08:57 UTC, merged