wireguard-go: use proper Go modules instead of git submodule
mullvad/mullvadvpn-app-binaries pull request #16
Opened 2019-03-22 10:33 UTC by zx2c4

Instead of having to do the insane submodule hack like before,
wireguard-go has finally gotten with the times and uses a proper Go
module with source code pinning via hashes (updatable with go-get). This
enables you to use the latest wireguard-go improvements, as well as Go
1.12.

This commit is entirely untested, but it appears to compile.

2019-03-22 13:22 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/16)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @pinkisemils and @zx2c4)

___
*[wireguard-go/go.mod, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/16#-La_YTMb4yGPlpoJ9JPO:-La_YTMc4OApd_Ivqfry:ba72wf6) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/329008a673bac264af9900b870985049aa9f0c70/wireguard-go/go.mod#L7)):*
> ```XML
> require (
> 	golang.org/x/sys v0.0.0-20190322080309-f49334f85ddc
> 	golang.zx2c4.com/wireguard v0.0.0-20190321212009-317d716d662f
> ```

Seems to me like this way of keeping track of the code requires us to store more metadata. And harder to update? The submodule was just `git checkout <where I want>` and commit the submodule change. But I don't know anything about golang dependency management, so I'll leave the review of this to someone else :)


<!-- Sent from Reviewable.io -->

2019-03-22 17:40 UTC, pinkisemils reviewed
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/16)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[wireguard-go/go.mod, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/16#-La_YTMb4yGPlpoJ9JPO:-LaaTsZF2z-IvTPBaFVz:bbh626a) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/329008a673bac264af9900b870985049aa9f0c70/wireguard-go/go.mod#L7)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Seems to me like this way of keeping track of the code requires us to store more metadata. And harder to update? The submodule was just `git checkout <where I want>` and commit the submodule change. But I don't know anything about golang dependency management, so I'll leave the review of this to someone else :)
</blockquote></details>

Go has tools for this, so it won't be any harder than managing a submodule. I think this is a worthy improvement - the previous version of this was the equivalent of using a submodule to vendor a library rather cargo and `Cargo.lock`.  


<!-- Sent from Reviewable.io -->

2019-03-22 19:08 UTC, faern approved these changes

2019-03-22 20:10 UTC, zx2c4 commented
I see you've approved this, cool. But I should reiterate: I haven't tested this commit. So while it's pretty clearly correct in terms of Go direction, I recommend you test it out before shipping this, since I haven't.

2019-04-01 19:16 UTC, pinkisemils approved these changes
I was trying to reply to this PR with a rather spotty connection, so clearly some things didn't quite get through. 
> All the changes look good, so I'm OK with merging this after we've tested that the library works on Linux and MacOS.
I've tested this on linux and MacOS, seems to just work :thumbsup: 

> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/16#-:-LaaUUmhCqzW-90rVnbc:bge1im)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2019-04-02 14:31 UTC, pinkisemils commented
I've rebased and merged this.

2019-04-02 14:31 UTC, closed without merging