Optimize android docker image
mullvad/mullvadvpn-app-binaries pull request #60
Opened 2020-02-05 12:38 UTC by pinkisemils

I've changed the Dockerfile in two meaningful ways:
- the NDK toolchains are now installed lazily. This reduces the size of the image from 3 to 1 gigabytes when compressed. Scripts ran in the container should use `install-ndk-toolchain $arch` where `$arch` is any of the short architecture name for the NDK (`arm64,arm,x86,x86_64`).
- Setup and patch a `go` toolchain so that it doesn't have to be done every time `wireguard-go` has to be compiled.

2020-02-05 14:07 UTC, jvff requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @jvff and @pinkisemils)

___
*[android-build/build.sh, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-KdVmC0EJYMZKUgnjp:-M-KdVmDC4tMVArKzW_1:b-cigv6o) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/c810cc5a9056850dcf14dec7e71d73799cf2b9b4/android-build/build.sh#L5)):*
> ```Shell
> set -e
> 
> for arch in arm arm64 x86_64 x86; do
> ```

Perhaps we could make the `arch` list a variable? And populate with all four platforms if it's not set externally.

I think it would allow the CI to only build for one platform by exporting the arch list variable before calling the script.
___
*[android-build/build.sh, line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-Kf2zECO28vWwR0HTI:-M-Kf2zG3o7hHgsCgBOP:bkjo94g) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/c810cc5a9056850dcf14dec7e71d73799cf2b9b4/android-build/build.sh#L33)):*
> ```Shell
>     esac
> 
>     install-ndk-toolchain $arch
> ```

Won't you need to prefix it with `./`? Also, it's probably a good idea to add a `.sh` suffix to it.
___
*[android-build/build.sh, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-KejZt4nyDlpErPxBn:-M-KejZt4nyDlpErPxBo:b-sgkdlv) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/c810cc5a9056850dcf14dec7e71d73799cf2b9b4/android-build/build.sh#L36)):*
> ```Shell
> 
>     export ANDROID_TOOLCHAIN_ROOT="/opt/android/toolchains/android21-${arch}"
>     export ANDROID_SYSROOT="/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
> ```

Something looks weird here. Why is it using `r20` in this line and `android21` in the line above?

Can't the path on this line and the one below be parameterized and passed to or obtained from the `install-ndk-toolchain` script?
___
*[android-build/install-ndk-toolchain, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-KeG7XCH6RXTneDxFK:-M-KeG7XCH6RXTneDxFL:bh7322h) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/c810cc5a9056850dcf14dec7e71d73799cf2b9b4/android-build/install-ndk-toolchain#L4)):*
> ```
> 
> set -eu
> mkdir -p /opt/androids/toolchains
> ```

Typo here `androids`.


<!-- Sent from Reviewable.io -->

2020-02-05 14:55 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @jvff)

___
*[android-build/build.sh, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-KdVmC0EJYMZKUgnjp:-M-KplZ-7Jlx8UtjSOUl:b-p8fafu) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/c810cc5a9056850dcf14dec7e71d73799cf2b9b4/android-build/build.sh#L5)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Perhaps we could make the `arch` list a variable? And populate with all four platforms if it's not set externally.

I think it would allow the CI to only build for one platform by exporting the arch list variable before calling the script.
</blockquote></details>

Maybe, but that's irrelevant here as when we're rebuilding OpenSSL for Android, I'd presume we always want all of the platforms be built anyway, right?
___
*[android-build/build.sh, line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-Kf2zECO28vWwR0HTI:-M-Klchz2dVhYFwCU-So:bqbqcva) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/c810cc5a9056850dcf14dec7e71d73799cf2b9b4/android-build/build.sh#L33)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Won't you need to prefix it with `./`? Also, it's probably a good idea to add a `.sh` suffix to it.
</blockquote></details>

It's put in `/usr/local/bin`. It's not actually contained in the current working directory.
___
*[android-build/build.sh, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-KejZt4nyDlpErPxBn:-M-Km-gF82IBpjcg18Iw:b-3rseve) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/c810cc5a9056850dcf14dec7e71d73799cf2b9b4/android-build/build.sh#L36)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Something looks weird here. Why is it using `r20` in this line and `android21` in the line above?

Can't the path on this line and the one below be parameterized and passed to or obtained from the `install-ndk-toolchain` script?
</blockquote></details>

`android21` is the directory that is the toolchain target. I think we could output all those export lines from `install-ndk-toolchain`. The discrepancy stems from the fact that we're targeting platform level 21, but the toolchain version is 20. 
___
*[android-build/install-ndk-toolchain, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-KeG7XCH6RXTneDxFK:-M-KpsR6A35FtUPKtGil:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/c810cc5a9056850dcf14dec7e71d73799cf2b9b4/android-build/install-ndk-toolchain#L4)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Typo here `androids`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-05 19:31 UTC, jvff reviewed
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60)* status: all files reviewed, 4 unresolved discussions (waiting on @jvff and @pinkisemils)

___
*[android-build/Dockerfile, line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-LpKTwCyYU5pxttKdb:-M-LpKTwCyYU5pxttKdc:b6677te) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/c810cc5a9056850dcf14dec7e71d73799cf2b9b4/android-build/Dockerfile#L34)):*
> ```Dockerfile
>     rm /tmp/go1.13.3.linux-amd64.tar.gz && \
>     patch -p1 -f -N -r- -d "/opt/go" < /opt/goruntime-boottime-over-monotonic.diff
> ENV PATH=${PATH}:/opt/go/bin
> ```

Minor: Maybe add newlines around the `RUN` command so it's easier to read?
___
*[android-build/install-ndk-toolchain, line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-LoJPF-vSKunAYQOc6:-M-LoJPF-vSKunAYQOc7:b-pnvkkg) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/c810cc5a9056850dcf14dec7e71d73799cf2b9b4/android-build/install-ndk-toolchain#L30)):*
> ```
> for lib in crtbegin_dynamic.o crtend_android.o crtbegin_so.o crtend_so.o; do
>     ln -s "/opt/android/toolchains/android21-${target_arch}/sysroot/usr/lib/${llvm_arch}/21/$lib" \
>           /opt/android/toolchains/android21-${target_arch}/sysroot/usr/lib/${llvm_arch}/;
> ```

Nit: You can remove the semicolon at the end.


<!-- Sent from Reviewable.io -->

2020-02-05 19:33 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60)* status: all files reviewed, 4 unresolved discussions (waiting on @jvff and @pinkisemils)

___
*[android-build/build.sh, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-KejZt4nyDlpErPxBn:-M-LpcXWAnjIoWx9Vm3d:b5150jy) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/c810cc5a9056850dcf14dec7e71d73799cf2b9b4/android-build/build.sh#L36)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

`android21` is the directory that is the toolchain target. I think we could output all those export lines from `install-ndk-toolchain`. The discrepancy stems from the fact that we're targeting platform level 21, but the toolchain version is 20. 
</blockquote></details>

Ah, now I got it :D

Yeah, maybe it's a good idea to export the lines from the script, but I'll leave the final decision to you :)


<!-- Sent from Reviewable.io -->

2020-02-06 01:18 UTC, jvff requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[android-build/build.sh, line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-N3j08AAQmyIp1q2dH:-M-N3j09903K6zwWsePR:b21uwwy) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a38e49ba48be763fce0fa1a13684e2ccc1ffc601/android-build/build.sh#L36)):*
> ```Shell
> 
>     export ANDROID_TOOLCHAIN_ROOT="/opt/android/toolchains/android21-${arch}"
>     export ANDROID_SYSROOT="/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
> ```

Maybe use the `$ANDROID_TOOLCHAIN_ROOT` here as well?
___
*[android-build/build.sh, line 37 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-N3m_nBYE1770Z9JbD:-M-N3m_nBYE1770Z9JbE:bo3h4vq) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a38e49ba48be763fce0fa1a13684e2ccc1ffc601/android-build/build.sh#L37)):*
> ```Shell
>     export ANDROID_TOOLCHAIN_ROOT="/opt/android/toolchains/android21-${arch}"
>     export ANDROID_SYSROOT="/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
>     export ANDROID_C_COMPILER="/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target=$ANDROID_LLVM_TRIPLE"
> ```

I think this line was supposed to be removed.


<!-- Sent from Reviewable.io -->

2020-02-06 12:05 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[android-build/build.sh, line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-N3j08AAQmyIp1q2dH:-M-PFiMx0m3_B-dU506F:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a38e49ba48be763fce0fa1a13684e2ccc1ffc601/android-build/build.sh#L36)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Maybe use the `$ANDROID_TOOLCHAIN_ROOT` here as well?
</blockquote></details>

Done.
___
*[android-build/build.sh, line 37 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-M-N3m_nBYE1770Z9JbD:-M-PFhuYBUR1VIVRycFS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app-binaries/blob/a38e49ba48be763fce0fa1a13684e2ccc1ffc601/android-build/build.sh#L37)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think this line was supposed to be removed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-06 13:30 UTC, jvff approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app-binaries/60#-:-M-PgUIxEc7zNhx-39bz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-02-06 16:13 UTC, merged